db-uri = "postgres://postgres@localhost:5433/app"
db-schemas = "public"
db-anon-role = "anon"
db-pool = 10
server-port = 3001
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt-role-claim-key = ".role"
db-max-rows = 1000
db-prepared-statements = false
